change sent/received fields in client usage history to 64-bit
Currently we get json deserialization errors because these fields are defined as 32-bit

Newtonsoft.Json.JsonReaderException: JSON integer 2466567113 is too large or small for an Int32. Path '[76].sent', line 1, position 5428.

Newtonsoft.Json.JsonReaderException: JSON integer 2661439858 is too large or small for an Int32. Path '[219].received', line 1, position 15151.